package com.util;

import com.util.MailUtil.*;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.Test;

import java.util.Date;
import java.util.Properties;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.MimeMessage;



import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.naukri.NaukriLaunch;
import com.properties.PropReader;
public class MailUtilTest {

		@Test
	public void mail_A$String$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		MailUtil target = new MailUtil();
		String subject = "test subject";
		String body = "test body";
		Assert.assertTrue(target.mail(subject, body));
	}

}
